import Footer from '@/components/shared/Footer';
import Navbar from '@/components/shared/Navbar';
import ResponsiveNavbar from '@/components/shared/ResponsiveNavbar';
import MainProvider from '@/contexts/MainProvider';
import './globals.css';

export const metadata = {
  title: 'Food System By ahmed ashraf',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='ar' dir='rtl'>
      <body className='font-arb'>
        <MainProvider>
          {/* Navbar */}
          <Navbar />
          {/* Responsive Navbar */}
          <div className='block md:hidden'>
            <ResponsiveNavbar />
          </div>
          {children}
          {/* Footer */}
          <Footer />
        </MainProvider>
      </body>
    </html>
  );
}
